"""
features.py
-----------
Forensic feature extraction for tamper detection.

1. Error Level Analysis (ELA): resave the image at a known JPEG quality and
   diff against the original. Regions that were edited *after* the image's
   last save (or spliced in from a different-quality source) tend to have a
   different re-compression error than the rest of the image, showing up as
   a brighter patch in the ELA map. This is a decades-old but still-standard
   forensic technique used in real document/image forgery pipelines.

2. Handcrafted statistical features (for the classical ML baseline): mean /
   std / max of the ELA map, plus local noise-variance features from a
   Laplacian filter, used to catch splicing/recompression without a CNN.
"""
import io
import numpy as np
from PIL import Image, ImageChops

# DocuGuard cards use a FIXED template layout (only text content differs
# card-to-card), so unlike arbitrary natural photos we know in advance
# exactly which screen regions can ever contain tamperable content: the
# photo box, each of the 7 text-field rows, the signature, and the barcode
# strip. Scanning ELA/noise stats at these known ROIs (rather than a blind
# whole-image grid) avoids the false signal generated by naturally
# high-frequency content (crisp text edges, barcode bars) that's present on
# every card regardless of whether it was tampered with.
TEMPLATE_ROIS = {
    "avatar": (24, 66, 184, 266),
    "field_0": (195, 64, 420, 100),
    "field_1": (195, 104, 420, 140),
    "field_2": (195, 144, 420, 180),
    "field_3": (195, 184, 420, 220),
    "field_4": (195, 224, 420, 260),
    "field_5": (195, 264, 420, 300),
    "field_6": (195, 304, 420, 340),
    "signature": (24, 280, 184, 320),
    "barcode": (200, 366, 620, 386),
}


def compute_ela(img: Image.Image, quality: int = 90) -> Image.Image:
    """Returns a grayscale ELA map (same size as input) as a PIL Image."""
    if img.mode != "RGB":
        img = img.convert("RGB")
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=quality)
    buf.seek(0)
    resaved = Image.open(buf)
    diff = ImageChops.difference(img, resaved)
    arr = np.asarray(diff).astype(np.float32)
    scale = 255.0 / (arr.max() + 1e-6)
    ela = (arr * scale).clip(0, 255).astype(np.uint8)
    ela_gray = Image.fromarray(ela).convert("L")
    return ela_gray


def ela_stats(ela_img: Image.Image) -> dict:
    arr = np.asarray(ela_img).astype(np.float32)
    h, w = arr.shape
    # split into a fine grid (~40x40px cells) and take per-cell stats -> a
    # small tampered patch dominates its own cell instead of being diluted
    # the way a single global mean/std or a coarse grid would dilute it
    gh, gw = max(1, h // 10), max(1, w // 16)
    cell_means = []
    for r in range(0, h, gh):
        for c in range(0, w, gw):
            cell = arr[r:r + gh, c:c + gw]
            if cell.size:
                cell_means.append(cell.mean())
    cell_means = np.array(cell_means)
    global_med = float(np.median(arr))
    # Note: a tampered patch can show EITHER higher or lower ELA response
    # than its surroundings depending on relative compression history (a
    # region that was already compressed at low quality tends to read
    # *darker* under ELA than fresh/never-compressed content, not brighter
    # as the textbook "bright = fake" intuition suggests) -- so we compute
    # sign-agnostic deviation-from-background features and let the model
    # learn which direction is discriminative for a given case.
    abs_dev = np.abs(cell_means - global_med)
    return {
        "ela_mean": float(arr.mean()),
        "ela_std": float(arr.std()),
        "ela_max": float(arr.max()),
        "ela_p95": float(np.percentile(arr, 95)),
        "ela_p99": float(np.percentile(arr, 99)),
        "ela_cell_std": float(cell_means.std()),
        "ela_cell_max": float(cell_means.max()),
        "ela_cell_min": float(cell_means.min()),
        "ela_cell_max_dev": float(abs_dev.max()),        # biggest |cell - background| anomaly
        "ela_cell_dev_std": float(abs_dev.std()),
    }


def laplacian_noise_variance(img: Image.Image) -> float:
    import cv2
    arr = np.asarray(img.convert("L"))
    lap = cv2.Laplacian(arr, cv2.CV_64F)
    return float(lap.var())


def roi_feature_vector(img: Image.Image) -> np.ndarray:
    """
    Region-aware feature vector for the classical ML baseline: per known
    template ROI (avatar/each field row/signature/barcode), compute ELA
    mean+max and Laplacian noise variance, then also add the single
    highest-anomaly ROI's deviation from the OTHER ROIs' median -- this is
    what actually isolates a tampered field from the card's own normal
    high-frequency content (text/barcode), which whole-image global stats
    could not do (see notebooks/eda for the ablation).
    """
    import cv2
    ela = compute_ela(img, quality=90)
    ela_arr = np.asarray(ela).astype(np.float32)
    gray = np.asarray(img.convert("L")).astype(np.float64)

    roi_means, roi_maxs, roi_noise = [], [], []
    for (x0, y0, x1, y1) in TEMPLATE_ROIS.values():
        x0, y0 = max(0, x0), max(0, y0)
        x1, y1 = min(ela_arr.shape[1], x1), min(ela_arr.shape[0], y1)
        cell = ela_arr[y0:y1, x0:x1]
        gcell = gray[y0:y1, x0:x1]
        if cell.size == 0:
            roi_means.append(0.0); roi_maxs.append(0.0); roi_noise.append(0.0)
            continue
        roi_means.append(float(cell.mean()))
        roi_maxs.append(float(cell.max()))
        roi_noise.append(float(cv2.Laplacian(gcell, cv2.CV_64F).var()) if gcell.size > 4 else 0.0)

    roi_means = np.array(roi_means)
    roi_noise = np.array(roi_noise)
    med_mean, mad_mean = np.median(roi_means), np.median(np.abs(roi_means - np.median(roi_means))) + 1e-6
    med_noise, mad_noise = np.median(roi_noise), np.median(np.abs(roi_noise - np.median(roi_noise))) + 1e-6
    max_anomaly_mean = float(np.max(np.abs(roi_means - med_mean)) / mad_mean)     # robust z-score style outlier
    max_anomaly_noise = float(np.max(np.abs(roi_noise - med_noise)) / mad_noise)

    vec = roi_means.tolist() + roi_maxs + roi_noise.tolist() + [max_anomaly_mean, max_anomaly_noise]
    return np.array(vec, dtype=np.float32)


def roi_feature_names() -> list:
    names = []
    for k in TEMPLATE_ROIS:
        names.append(f"{k}_ela_mean")
    for k in TEMPLATE_ROIS:
        names.append(f"{k}_ela_max")
    for k in TEMPLATE_ROIS:
        names.append(f"{k}_noise_var")
    names += ["max_anomaly_mean_zscore", "max_anomaly_noise_zscore"]
    return names


def extract_feature_vector(img: Image.Image) -> np.ndarray:
    """Handcrafted feature vector for the classical ML baseline model."""
    return roi_feature_vector(img)


FEATURE_NAMES = roi_feature_names()


if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.path.dirname(__file__))
    from synth_id_generator import IDRecord, render_card
    from tamper import apply_random_tamper

    rec = IDRecord.random(seed=99)
    img, boxes, _ = render_card(rec)
    tampered, bbox, attack = apply_random_tamper(img, boxes, seed=99)

    ela_auth = compute_ela(img)
    ela_tamp = compute_ela(tampered)
    os.makedirs("data/samples", exist_ok=True)
    ela_auth.save("data/samples/ela_authentic.png")
    ela_tamp.save("data/samples/ela_tampered.png")
    print("authentic features:", extract_feature_vector(img))
    print("tampered  features:", extract_feature_vector(tampered), "attack:", attack)
